Repository projectdiscovery/utils, pull requests merged in 2022-11, with the labels that each got.

#17 test cases addition mapsutil
  maps/mapsutil_test.go
Labels: Type: Maintenance

#18 move packages from naabu
  go.mod
  go.sum
  permission/README.md
  permission/error.go
  permission/permission.go
  permission/permission_darwin.go
  permission/permission_linux.go
  permission/permission_win.go
  race/README.md
  race/norace.go
  race/race.go
Labels: Type: Maintenance

#20 IsInternal function
  ip/iputil.go
  ip/iputil_test.go
Labels: Type: Maintenance

#22 suffix props tests sleep time
  file/file_test.go
Labels: Type: Bug

#24 exec: Windows Exec support and Safe Mode
  exec/executil.go
  exec/executil_test.go
Labels: Type: Enhancement
