Repository projectdiscovery/utils, pull requests merged in 2023-01, with the labels that each got.

#41 adding helpers + tests
  slice/sliceutil.go
  slice/sliceutil_test.go
Labels: Type: Enhancement

#51 Fixing autorelease
  .github/workflows/release-tag.yml
Labels: Type: Maintenance

#52 Adding support for nil errors
  errors/errors.go
Labels: Type: Bug

#58 Adding context utils
  context/context.go
  context/context_test.go
Labels: Type: Maintenance

#57 Addind os/arch utils
  os/arch.go
  os/os.go
Labels: Type: Maintenance

#49 Add helper function to count lines in files
  file/file.go
  file/file_test.go
  file/tests/test.txt
  file/tests/test_empty_space.txt
  file/tests/test_pipe_separator.txt
Labels: Type: Enhancement
