Repository projectdiscovery/utils, pull requests merged in 2023-08, with the labels that each got.

#232 add default permissions
  permission/permission_file.go
Labels: Type: Maintenance

#215 Adding value or default context helper
  context/context.go
  context/context_test.go
Labels: Type: Enhancement

#238 Fixing conditional build
  permission/permission_file.go
Labels: Type: Bug

#239 introduce generic lockable type
  generic/lockable.go
  generic/lockable_test.go
Labels: Type: Enhancement

#242 add UpdateWithEnv func and default values
  env/env.go
  env/env_test.go
Labels: Type: Enhancement

#241 improve home folder detection
  folder/folderutil.go
  folder/folderutil_test.go
Labels: Type: Enhancement

#250 add HasPrefixAnyI
  strings/stringsutil.go
  strings/stringsutil_test.go
Labels: Type: Enhancement

#248 add more unit test for url fragment parsing
  url/url.go
  url/url_test.go
Labels: Type: Maintenance
